name: Demo App Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: "Select Demo App environment"
        required: true
        default: "dev"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            dotnet/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Show tags
        run: |
          echo "Generated tags:"
          echo "${{ steps.meta.outputs.tags }}" | tr ',' '\n'
